version: '3.2'
services:
  odoo:
    container_name: odoo11
    depends_on:
      - postgres
    build:
      context: ./odoo
    volumes:
      - ${ProjectPath}:/etc/odoo
    links:
      - "postgres"
    ports:
      - "8069:8069"
    network_mode: "bridge"

  postgres:
    container_name: odoo11-db
    build:
      context: ./db
    ports:
      - "5432:5432"
    network_mode: "bridge"
